export const INSTAGRAM_URL: string = "https://instagram.com/mcpikon"
export const GITHUB_URL: string = "https://github.com/MCPikon"
export const TWITTER_URL: string = "https://x.com/mcpikon"
export const LINKEDIN_URL: string = "https://www.linkedin.com/in/javierpiconpastor/"
export const EMAIL: string = "javierpiconpastor@gmail.com"